### PR TITLE
upgrading graphite and removing grafana/es cruft

### PR DESCRIPTION
**Pull request by lamdor**

### CODE REVIEW

**Comment by adamdecaf** [comment]
FYI this is upgrading to contain the fix https://github.com/graphite-project/carbon/issues/383

**Comment by lamdor** [comment]
@adamdecaf It doesn't yet contain that as the graphite packages haven't been released yet.

**Comment by lamdor** [comment]
closes #3

**Comment by adamdecaf** [comment]
@rubbish Ah. I thought you were going to include that here once they were released.

**Comment by lamdor** [comment]
@adamdecaf i made it easier to upgrade when the time comes though.

**Comment by lamdor** [comment]
@Banno/infrastructure what do you guys think?

**Comment by nicgrayson** [comment]
:+1:

**Comment by daniellockard** [comment]
l g t m

**Pull request merged**
